<?xml version="1.0" encoding="utf-8"?><Database Name="dataDb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=desktop-5e70rm2;Initial Catalog=dataDb;Integrated Security=True;Pooling=False" SettingsObjectName="linq_to_sql.Properties.Settings" SettingsPropertyName="dataDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dog" Member="Dogs">
    <Type Name="Dog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bread" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
</Database>